version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
    steps:
      - checkout

      - run:
          name: Install system deps
          command: apt-get update && apt-get -f install libsqlite3-dev

      - run:
          name: Crystal version
          command: crystal --version

      - run:
          name: Shards version
          command: shards --version

      - restore_cache:
          keys:
            - crystal-v1-{{ checksum "shard.lock" }}
            - crystal-v1-

      - run:
          name: Install dependencies
          command: shards install

      - save_cache:
          key: crystal-v1-{{ checksum "shard.lock" }}
          paths:
            - ~/.cache/shards
            - lib

      - run:
          name: Lint code
          command: crystal tool format --check

      - run:
          name: Run unit / integration tests
          command: crystal spec

      - run:
          name: Build app
          command: shards build --release

      - run:
          name: Run CLI functional test
          command: bin/vulnsearch --version
