version: 2
jobs:
  build:
    docker:
      - image: golang:1.15-alpine
        environment:
          GOFLAGS: -trimpath -mod=readonly -modcacherw
    steps:
      - run:
          name: Install system deps
          command: apk add --no-cache --update gcc git make musl-dev sqlite

      - checkout

      - run:
          name: Go version
          command: go version

      - restore_cache:
          keys:
            - golang-deps-v1

      - run:
          name: Install dependencies
          command: make deps

      - save_cache:
          key: golang-deps-v1
          paths:
            - "/go/pkg"

      - run:
          name: Run tests
          command: make test

      - run:
          name: Lint code
          command: make lint

      - run:
          name: Build binary
          command: make build

      - run:
          name: Run CLI functional test
          command: vulnsearch --version

      - store_artifacts:
          path: coverage
          destination: coverage
