version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
    steps:
      - checkout

      - run:
          name: Install system deps
          command: apt-get -f install libsqlite3-dev

      - run:
          name: Crystal version
          command: crystal --version

      - run:
          name: Shards version
          command: shards --version

      - run:
          name: Install dependencies
          command: shards install

      - run:
          name: Lint code
          command: crystal tool format --check

      - run:
          name: Run tests
          command: crystal spec
