name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch dependencies
      run: |
        go mod download
        go mod verify

    - name: Lint code
      run: go vet ./...

    - name: Run tests
      run: |
        mkdir -p coverage
        go test -race -coverprofile coverage/cover.out -v ./...
        go tool cover -html coverage/cover.out -o=coverage/index.html

    - name: Build app
      run: go build

    - name: CLI functional test
      run: ./vulnsearch --help
